ChatLesh/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ClientModule.urls')),
    path('mesajlar/', include('ChatModule.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ClientModule/models.py
from django.db import models
from django.contrib.auth import password_validation
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.models import PermissionsMixin
from django.utils.crypto import salted_hmac

from .managers import UserManager


class User(PermissionsMixin):
    nick = models.CharField(verbose_name='Nickname', max_length=20, unique=True)
    ip = models.CharField(max_length=20, verbose_name='IP', unique=True)
    password = models.CharField(verbose_name='Şifre', null=True, blank=True, max_length=128)
    date_joined = models.DateTimeField(verbose_name='Kayıt Tarihi', auto_now_add=True)
    is_active = models.BooleanField('Aktif mi ?', default=True)
    is_staff = models.BooleanField(verbose_name='Yetkili mi ?', default=False)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'nick'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Kullanıcılar'
        verbose_name_plural = 'Kullanıcılar'

    def __str__(self):
        return self.nick

    def set_password(self, raw_password):
        self.password = make_password(raw_password)
        self._password = raw_password

    def check_password(self, raw_password):
        def setter(raw_password):
            self.set_password(raw_password)
            self._password = None
            self.save(update_fields=["password"])
        return check_password(raw_password, self.password, setter)

    @property
    def is_anonymous(self):
        return False

    @property
    def is_authenticated(self):
        return True

    def get_session_auth_hash(self):
        key_salt = "django.contrib.auth.models.AbstractBaseUser.get_session_auth_hash"
        return salted_hmac(key_salt, self.password).hexdigest()


class UserFriends(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend')
    accept = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.nick

templates/client/friendRequestAcceptModal.html
<i class="close icon"></i>
<div class="header">
    {{ friendRequest.user.nick }} friend request
</div>
<div class="image content">
    <div class="ui medium image">
        <img src="{{ friendRequest.user.avatar.url }}">
    </div>
    <div class="description">
        <div class="ui header">Do you want to accept {{ friendRequest.user.nick }} friend request ?</div>
        <p>If accept this request {{ friendRequest.user.nick }} can send you a message</p>
    </div>
</div>
<div class="actions">
    <div class="ui black deny button">
        NO
    </div>
    <div onclick="acceptRequest('{{ friendRequest.id }}')" class="ui positive right labeled icon button">
        YES
        <i class="checkmark icon"></i>
    </div>
</div>
<script>
    function acceptRequest(requestID) {
        $.ajax({
            url: "{% url "acceptRequest" %}",
            type: "post",
            data: {
                csrfmiddlewaretoken: "{{ csrf_token }}",
                requestID: requestID
            },
            success: function (result) {
                if (result.msg === 'success') {
                    $('#friendshipModal').modal('close');
                } else {
                    alert("Opps! Some error occured...");
                }
            }
        })
    }
</script>

templates/client/friendshipRequestModal.html
<i class="close icon"></i>
<div class="header">
    Friend Request
</div>
<div class="image content">
    <div class="ui medium image">
        <img src="{{ friend.avatar.url }}">
    </div>
    <div class="description">

        {% if isWaiting %}
            <div class="ui header">
                Your friend request is not accepted yet!
            </div>
            <p>
                {{ friend.nick }} is not accept your request yet.
            </p>
        {% else %}
            <div class="ui header">
                Your friend request is sent successfully.
            </div>
            <p>
                You can chat with {{ friend.nick }} after your request accepted.
            </p>
        {% endif %}

    </div>
</div>
<div class="actions">
    <div class="ui green deny button">
        OK
    </div>
</div>

templates/client/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <div class="ui top attached menu">
        <a href="/" class="item">
            <img src="{% static "imagefiles/logo.png" %}" alt="chatLeshLogo">
        </a>
        <a class="item online-users">
            <i class="users icon"></i> Online Users
        </a>
        <a class="notify item" onclick="clearAnimation(notifyInterval, $(this).attr('id'))" id="notifyMenu">
            <i class="globe icon"></i> Notifications
        </a>
        <a href="{% url "logout" %}" id="logoutBtn" class="item right floated">
            <i class="power off icon"></i> Log Out
        </a>
    </div>
    <div class="ui flowing basic admission popup">
        <div class="ui column relaxed divided grid">
            <div class="column">
                <div class="ui link list" id="notifyList">
                    {% for foo in friendRequests %}
                        <script>
                            requestsID.push({{ foo.id }});
                        </script>
                        <a onclick="friendRequestAccept('{{ foo.id }}')" class="item">{{ foo.user.nick }} is send you a friend request.</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="ui bottom attached segment">
        <div class="ui labeled icon left inline vertical demo sidebar menu" id="onlineUserList"></div>
        <div class="pusher">
            <div class="ui basic segment" id="chatPanelDiv"></div>
        </div>
    </div>
    <div class="ui modal" id="friendshipModal"></div>
{% endblock %}
{% block scripts %}
    <script>
        $('.ui.sidebar').sidebar({
            context: $('.bottom.segment'),
            transition: 'scale down'
        }).sidebar('attach events', '.menu .online-users');
        $('a.notify.item')
            .popup({
                popup: $('.ui.flowing.basic.admission.popup'),
                on: 'click',
                position: 'bottom left',
                lastResort: true,
            })
        ;
    </script>
    <script type="text/javascript" src="{% static "websocket.min.js" %}"></script>
    <script>
        function loadChatPanel(threadID) {
            $.ajax({
                url: "/mesajlar/openChatPanel/"+threadID+"/",
                success: function (result) {
                    $('#chatPanelDiv').html("").append(result)
                }
            })
        }

        function friendOrChatRequest(usernickName) {
            $.ajax({
                url: "{% url "friendOrChatRequest" %}",
                type: "post",
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    usernickName: usernickName
                },
                success: function (result) {
                    if (result.msg === 'openChat') {
                        console.log("openchat");
                        loadChatPanel(''+result.threadID+'');
                    } else {
                        $('#friendshipModal').html("").append(result).modal('show');
                    }
                }
            })
        }

        function friendRequestAccept(requestID) {
            $.ajax({
                url: "{% url "friendRequestAccept" %}",
                type: "post",
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    requestID: requestID
                },
                success: function (result) {
                    $('#friendshipModal').html("").append(result).modal("show");
                }
            })
        }
        function fadeInfadeOut(elementID) {
            notifyInterval = setInterval(function () {
                var sendedElement = $('#'+elementID+'');
                sendedElement.css('color', 'red').find('i').css('color', 'red');
                sendedElement.fadeOut(1000).fadeIn(1000);
            }, 1000)
        }

        function clearAnimation(sendedInternal, elementID) {
            clearInterval(sendedInternal);
            var sendedElement = $('#'+elementID+'');
            sendedElement.css('color', 'black').find('i').css('color', 'black');
        }

        {% if friendRequests|length > 0 %}
            fadeInfadeOut('notifyMenu');
        {% endif %}

        function checkFriendRequest() {
            $.ajax({
                url: "{% url "checkFriendRequests" %}",
                type: "post",
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success: function (result) {
                    $('#notifyList').html("");
                    $.each(result, function (key, val) {
                        if (jQuery.inArray(val.requestID, requestsID) !== -1) {
                            $('#notifyList').html("").append(
                                '<a onclick="friendRequestAccept(\'' + val.requestID + '\')" class="item">' + val.friendNick + ' is send you a friend request</a>'
                            )
                        } else {
                            requestsID.push(val.requestID);
                            fadeInfadeOut('notifyMenu');
                            friendRequestAccept(""+val.requestID+"");
                        }
                    })
                }
            })
        }

        function checkOnlineUsers(type) {
            $.ajax({
                url: "{% url "onlineUsers" %}",
                type: "post",
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    nick: "{{ request.user.nick }}",
                    ip: "{{ request.user.ip }}",
                    type: type
                },
                success: function (result) {
                    $('#onlineUserList').html("");
                    $.each(result, function (key, value) {
                        var currentUser = '{{ request.user }}';
                        if (currentUser !== value.userNickName) {
                            $('#onlineUserList').append(
                                '<a class="item" onclick="friendOrChatRequest(\'' + value.userNickName + '\')">' +
                                '<img width="50" height="50" style="border-radius: 50%;" src="' + value.userAvatar + '">' +
                                '<span>' + value.userNickName + '<span>' +
                                '</a>'
                            )
                        }
                    })
                }
            });
        }

        $(document).ready(function () {
            setInterval(function () {
                checkOnlineUsers('onOpen');
                checkFriendRequest();
            }, 15000);
        });
        $(function () {
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var chatsock = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + ':8001/mesajlar/connect/');

            chatsock.onopen = function () {
                checkOnlineUsers('onOpen')
            };

            $('#logoutBtn').on('click', function () {
                chatsock.close();
                checkOnlineUsers('onClose');
            });
        });
    </script>
{% endblock %}

templates/client/login.html
{% extends 'base.html' %}
{% block body %}
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <h2 class="ui teal image header">
                <div class="content">
                    Sign-in | Sign-up your account
                </div>
            </h2>
            <form class="ui large form" name="LogRegForm" method="post" enctype="multipart/form-data">
                {% if loginError %}
                    <div class="ui message">
                        <div class="header">
                            {{ loginError }}
                        </div>
                    </div>
                {% endif %}

                {% csrf_token %}
                <div class="ui stacked segment">
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="user icon"></i>
                            <input type="text" required name="nickName" placeholder="Enter Nick Name">
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="globe icon"></i>
                            <input type="text" required name="ipAddress" value="{{ userIP }}">
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="file icon">Avatar</i>
                            <input type="file" id="id_avatar" name="avatar">
                        </div>
                    </div>
                    <button type="submit" class="ui fluid large teal submit button">Confirm</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}